name: get_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0
  google_sign_in: ^7.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.2
  http: ^1.6.0
  webview_flutter: ^4.13.1
  flutter_polyline_points: ^3.1.0
  shared_preferences: ^2.5.3
  webview_flutter_android: ^4.10.1
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^20.1.0
  firebase_crashlytics: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/getit_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2979FF"
  adaptive_icon_foreground: "assets/icons/getit_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700