// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArA6NV9tbzeTJoyTi2tzcf-tOBgJW0ivY',
    appId: '1:347991149828:web:40e1328924676ca890d451',
    messagingSenderId: '347991149828',
    projectId: 'getit-db879',
    authDomain: 'getit-db879.firebaseapp.com',
    storageBucket: 'getit-db879.firebasestorage.app',
    measurementId: 'G-KR0556HS63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAEkbVzAH_nPe2Q6ofFxS7qHTSNufYGlg',
    appId: '1:347991149828:android:2b6c9db7111125df90d451',
    messagingSenderId: '347991149828',
    projectId: 'getit-db879',
    storageBucket: 'getit-db879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZiBVL70t5gBAxIV5jgsU4mwft_Uy-Y0',
    appId: '1:347991149828:ios:310a2d95180ede2b90d451',
    messagingSenderId: '347991149828',
    projectId: 'getit-db879',
    storageBucket: 'getit-db879.firebasestorage.app',
    iosBundleId: 'com.example.getIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZiBVL70t5gBAxIV5jgsU4mwft_Uy-Y0',
    appId: '1:347991149828:ios:310a2d95180ede2b90d451',
    messagingSenderId: '347991149828',
    projectId: 'getit-db879',
    storageBucket: 'getit-db879.firebasestorage.app',
    iosBundleId: 'com.example.getIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArA6NV9tbzeTJoyTi2tzcf-tOBgJW0ivY',
    appId: '1:347991149828:web:64a13f7673eb9a7890d451',
    messagingSenderId: '347991149828',
    projectId: 'getit-db879',
    authDomain: 'getit-db879.firebaseapp.com',
    storageBucket: 'getit-db879.firebasestorage.app',
    measurementId: 'G-3X1M4TTT06',
  );

}